const projects = [
  {
    id: 1,
    name: "Spotify Clone",
    live_link: "https://spotify-clone-sooty-nine.vercel.app",
    github: "https://github.com/prthmh/spotify_clone",
    tech_stack: ["Next JS", "React JS", "Tailwind CSS", "Supabase", "React Hook Form", "Radix UI"],
    description: `A spotify clone, where users can upload their own songs, can like a song and add it to their playlist`,
  },
  {
    id: 2,
    name: "ChirpBox",
    live_link: "https://chirpbox.netlify.app/",
    github: "https://github.com/prthmh/ChirpBox",
    tech_stack: [
      "JavaScript",
      "React JS",
      "MockBee",
      "React Context API",
      "React Router",
      "React Toastify",
    ],
    description: `A social media app, where users can create posts, like, dislike, and bookmark posts for future reference.`,
  },
  {
    id: 3,
    name: "RupiyaTrackr",
    live_link: "https://rupiyatrackr.netlify.app/",
    github: "https://github.com/prthmh/RupiyaTrackr",
    tech_stack: [
      "JavaScript",
      "React JS",
      "Redux with Redux Thunk",
      "Node JS",
      "Express JS",
      "Mongoose",
      "MongoDB",
    ],
    description: `A fullstack finance management app. Users can add new income, expenses, savings and then manage them. `,
  },
  {
    id: 4,
    name: "Voom",
    live_link: "https://voom-inky.vercel.app/",
    github: "https://github.com/prthmh/zoom-clone",
    tech_stack: [
      "Next JS",
      "React JS",
      "TypeScript",
      "Clerk",
      "getstream",
      "Shadcn UI",
      "Tailwind CSS",
    ],
    description: `Fully responsive meeting platform(zoom clone). Users can initiate or schedule meetings, manage every aspect of meeting, from recording to participant controls.`,
  },
  {
    id: 5,
    name: "Appointo",
    live_link: "https://appointment-booking-screen.netlify.app/",
    github: "https://github.com/prthmh/appointment_booking",
    tech_stack: ["JavaScript", "React JS", "React Hot Toast", "React Icons"],
    description: `A dynamic appointment booking screen using React. On selecteing a date from calender and time-slot user will get atoast message.`,
  },
  {
    id: 6,
    name: "ChocoCart",
    live_link: "https://chococart.netlify.app/",
    github: "https://github.com/prthmh/ChocoCart",
    tech_stack: [
      "JavaScript",
      "React JS",
      "MockBee",
      "React Context API",
      "React Router",
      "React Toastify",
    ],
    description: `ChocoCart is an e-commerce application to buy different kinds of chocolates.`,
  },
];

export default projects;
